### PR TITLE
add an explicit test to delete collaborators

### PR DESCRIPTION
**Pull request by adamralph**

### CODE REVIEW

**Comment by sergioc** [comment]
@adamralph why was this issue in the collaboration repo?

**Comment by adamralph** [comment]
@sergioc you mean on the Collaboration waffle board? Good question. I'm having a hard time finding a strategic home for pbot features and bugs and other automation so I thought Collaboration was the best fit (it's certainly not part of Platform Dev). It raises the question of how we should visualise all internal automation work in one place.

**Comment by sergioc** [comment]
@adamralph since pbot is cross-strategy, it makes sense to track in collaboration. But would this kind of strategy scale to track the many repos we have?

**Comment by adamralph** [comment]
@sergioc I'm not really sure if it can scale to all the other repos. We have plenty of other things such as the Automation.* repos, etc. If they are all started to appear in Collaboration I think we may get drowned in technical issues in that strategy. I've sometimes wondered if we need a sixth "Automation" strategy.

**Pull request merged**
