### PR TITLE
Fixes #20

### LINKED ISSUE #20: Check if PBot has access to repository when adding new repositories
Improvement of an existing command `pbot add repo <name of repo>` to check if pbot has access to the repo. In case it doesn't, prevent pbot from adding this repo until pbot can access it. Present a warning message with appropriate instructions.

### PR DESCRIPTION
**Pull request by SeanFeldman**
@Particular/pbot please review.

Looks like we're using a live account for testing, which could result in bad things :)

### CODE REVIEW

**Comment by andreasohlund** [comment]
Code changes looks good to me.

Test is failing on the build server though?

**Comment by SeanFeldman** [comment]
That's odd, since all tests are passing when running locally. @andreasohlund could you please verify on your end?

**Comment by SeanFeldman** [comment]
Fixed.

**Comment by SeanFeldman** [comment]
@Particular/pbot please review

**Comment by distantcam** [comment]
+1 looks good

**Pull request merged**
