### PR TITLE
Ability to update requirements in a really simple way

### PR DESCRIPTION
**Pull request by danielmarbach**
@Particular/pbot Please review and merge

### CODE REVIEW

**Comment by adamralph** [comment]
From reading the test, it seems that this command takes the current requirement description, and inserts the requirement template before it, is that correct?

**Comment by danielmarbach** [comment]
Yes. Super dumb I know but a good starting point

Am Dienstag, 9. Juni 2015 schrieb Adam Ralph :

**Comment by adamralph** [comment]
I wonder if the command name could convey the semantics a little better? E.g.

`pbot insert template 123`

That way if you run it twice you expect to see the template twice. That would be a surprising result of 2 x `pbot update requirement 123`

**Comment by adamralph** [comment]
Sorry, it would have to reference requirements somewhere. Perhaps if we have a convention for templates and repos then it could be a general command for all repos, e.g.

`pbot add template requirements 123`

**Comment by danielmarbach** [comment]
If you merge it feel free to rename ;)

Am Dienstag, 9. Juni 2015 schrieb Adam Ralph :

**Comment by danielmarbach** [comment]
@adamralph should we close this?

**Comment by adamralph** [comment]
@danielmarbach sure

**Pull request closed without merging**
