### PR TITLE
Code to extract release stats

### PR DESCRIPTION
**Pull request by andreasohlund**

### CODE REVIEW

**Comment by sergioc** [comment]
@andreasohlund why was this issue in the collaboration repo?

**Comment by andreasohlund** [comment]
@sergioc not following? (this is the pbot repo)

**Comment by sergioc** [comment]
@andreasohlund somehow this issue showed up in the Collaboration waffle board, that's why I asked. We'll investigate that further. CC // @adamralph

**Comment by adamralph** [comment]
https://github.com/Particular/PBot/pull/62#issuecomment-168630745

**Pull request merged**
